on:
  push:
    branches: main
  schedule:
    - cron: '*/15 * * * *'

jobs:
  eqnz-dashboard:
    runs-on: ubuntu-latest
    steps:
      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Install packages
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages: |
            any::tidyverse
            any::httr2
            any::sf
            any::glue
            any::gt
            any::scales
            any::ggtext
            any::leaflet
            any::quarto
            
      - name: Set up quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Check out repository
        uses: actions/checkout@v3

      - name: Update dashboard
        run: Rscript -e 'source("render-dashboard.r")'

      - name: Commit results
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add index.html
          git commit -m 'Dashboard updated' || echo "No changes to commit"
          git push origin || echo "No changes to commit"